### ISSUE TITLE
Some robots have a polluted $ROS_PACKAGE_PATH

### ISSUE THREAD

**Issue by fishr** [mit212/prc#3]
Isn't an issue, just curious.

**Comment by fishr** [comment]
http://wiki.ros.org/catkin/what#SUPER_SUBTLE_SECRET_BEHAVIOR

Turns out adding a  catkin workspace can persist depending on certain conditions.

It also will pollute the $CMAKE_PREFIX_PATH so definitely a var to clean up when done with a workspace

``` bash
rm build/catkin_generated/installspace/_setup_util.py
rm devel/_setup_util.py
unset CMAKE_PREFIX_PATH
source /opt/ros/$ROS_DISTRO/setup.sh
catkin_make --force-cmake
```

**Comment by peterkty** [comment]
Is there an example for this?

Peter

**Comment by fishr** [comment]
I'm not 100% sure how to duplicate.  I think if one were to catmake a lab, rebash, then catmake prc, the env setup scripts for prc will have the lab's catkin_ws locked in.  You have to then remove the generated scripts to get rid of the extra workspace references.

robot010 had lab3_sol stuck in its $ROS_PACKAGE_PATH, this was the fix I found to get rid of it

**Comment by fishr** [comment]
You can see it right now on robot010 if you setenv lab4, then rebash, then echo $ROS_PACKAGE_PATH

its got prc, lab3_sol and lab4 all in the path.  pokebot is too, but that's from a different issue
